#!/bin/bash

set -eo pipefail

#
# This script deploys the build artifact to Pantheon.
# On the master branch the dev environment is used.
# Otherwise a multidev environment is used.
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Prepare for Pantheon
composer run prepare-for-pantheon

if [[ $CI_BRANCH != $DEFAULT_BRANCH ]]
then
    if [[ $CI_BRANCH == "staging" ]]
    then
        # Create a new multidev environment (or push to an existing one)
        terminus -n build:env:create "$TERMINUS_SITE.dev" "staging" --yes
        TERMINUS_ENV="staging"
    else
        terminus -n build:env:create "$TERMINUS_SITE.dev" "$CI_BRANCH" --yes
        TERMINUS_ENV="$CI_BRANCH"
    fi
else
    # Push to the dev environment
    terminus -n build:env:push "$TERMINUS_SITE.dev" --yes
fi

# Run update-db to ensure that the cloned database is updated for the new code.
terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- core update-db

# Clear the site environment's cache
terminus -n env:clear-cache "$TERMINUS_SITE.$TERMINUS_ENV"


# Delete old multidev environments associated
# remove line above to automatically remove multidev (we commented in order 
# to avoid misunderstandings).
#terminus -n build:env:delete:ci $TERMINUS_SITE --keep=3 --yes
